version: '3.7'
services:
  app:
    build: .
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on: 
      - db
    env_file:
      - .dockerenv
  db:
    image: postgres:12-alpine
    restart: always
    env_file:
    - .dockerenv
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
